This is the first ever "useful" program written
in the ARTICLE. It's an esoteric programming
language made by me, Soic. I don't know what else to
write but i still to write code.
Now, it's time to print the first character in
the very cool debug console.
Here i go again to write code to a dumb
language. I don't really know what to. say, yes
i swapped the position of a period and a comma
just because i'm very, very, lazy.
Now, it's time to print the first character in
the very cool debug console.
Here i go yet again writing code to a dumb
language. Yes, i am very LAZY. Lazy Lazy Lazy
Lazy, laughing out loud, yes, i did this twice.
Now, i will print the first character in
the cool debug console yet again.
Now, i will print the first character in
the cool console yet again, again.
Ngl, i'm out of ideas now and i'm just
writing stuff. I need to write code.
I need to write a lot of code.
I'm tired, now i will just filler my way
out f f f f.
f0 f1 f2 f3 f4
f5 f6 f7 f8 f9 f10 f11. n1 n2
n3 n4 n5 n6 n7 n8 n9. n1 n2 n3 n4 n5 n6 n7 n8
n9 n10 n11 n12 n13 n14 n15 n16 n17 n18 n19 n20.
f means filler f f f f f f f f f f f.
f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11. n1 n2 n3
n4 n5 n6 n7 n8 n9 n10. n1 n2 n3 n4 n5 n6 n7 n8
n9 n10 n11 n12.
f f f f f f f f f f f f f f.
f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12. n1 n2
n3 n4 n5. n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 n11 n12
n13.
f f f f f f f f f f f f f f.
f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11. n1 n2
n3 n4 n5. n1 n2 n3 n4 n5 n6 n7 n8.
F f f f f f f f f f f f f f.
f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12. n1 n2
n3 n4 n5. n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 n11.
F f f f f f f f f f f f f f.
f1 f2 f3 f4 f5 f6 f7 f8 f9 f10 f11 f12. n1 n2
n3 n4 n5. n1 n2 n3 n4 n5 n6 n7 n8 n9 n10 n11 n12 n13.
F f f f f f f f f f f f f f.
